apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  APP_ENV: develop
  APP_PORT: "8080"
  LOG_LEVEL: info
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  CLOUD_SQL_INSTANCE: PROJECT_ID:REGION:INSTANCE_NAME